# Tomcat
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /iot-modbus-test

devtools:
  restart:
    enabled: true #是否支持热部署

iot:
  netty: # netty通讯
    server:
      open: true
      port: 4000
      thread: 10
      heart-beat-time: 30000 #心跳检测超时时间(单位：毫秒)
    client:
      open: false
      ips: 127.0.0.1,192.168.1.198 #设置读写器IP,多个使用英文逗号隔开
      port: 5000
      thread: 10
      device-group: 1
      heart-beat-time: 3000 #心跳发送间隔时间(单位：毫秒)
      reconnect-time: 5000 #断线重连间隔时间(单位：毫秒)
  serialport: #串口通讯
    open: true
    port: COM1
    netty: true #是否使用netty对数据进行拆包处理
    timeout: 5000 #链接超时时间，不使用netty对数据进行拆包处理时必填
    baudrate: 115200
    thread: 10
    sleep-time: 2 #接收数据休眠时间(单位：毫秒)，串口方式必填